/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Ley
 */
public class TestePanel extends javax.swing.JPanel {

    /**
     * Creates new form TestePanel
     */
    public TestePanel() {
        initComponents();
    }

    @Override
protected void paintComponent(Graphics g) {
super.paintComponent(g); // paint the background image and scale it to fill the entire space
ImageIcon icon = new ImageIcon("src/img/food.jpg");
        Image image = icon.getImage().getScaledInstance(
icon.getIconWidth() * (int)this.getSize().getWidth() / icon.getIconWidth(),
icon.getIconHeight() * (int)this.getSize().getHeight() / icon.getIconHeight(),
Image.SCALE_SMOOTH);
icon = new ImageIcon(image, icon.getDescription());
// BufferedImage img = new ImgUtils().scaleImage((int)this.getSize().getWidth()-6, (int)this.getSize().getHeight()-6,"src/img/button2.png");
g.drawImage(icon.getImage(), 0, 0, this);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
